version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/ws"
    versions:
    - 7.4.0
    - 7.4.1
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: "@google-cloud/pubsub"
    versions:
    - 2.10.0
    - 2.8.0
    - 2.9.0
  - dependency-name: "@aimee-blue/ab-contracts"
    versions:
    - 1.205.13
    - 1.205.14
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.4
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
