language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '10'
if: tag IS blank
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
stages:
  - name: test, build and publish
jobs:
  include:
    - stage: test, build and publish
      script:
        - time yarn run check
        - time yarn test
      deploy:
        provider: script
        script:
          - yarn release
        skip_cleanup: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(master|alpha|beta|\d+.x$|\d+.x.x$|\d+.\d+.x)$
