language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+(-\w+(\.\d+)?(@\w+))?$/
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: test, build and deploy
      script:
        - time yarn run check
        - time yarn test
      deploy:
        - provider: script
          script:
            - yarn release
          skip_cleanup: true
          on:
            branch:
              - release
              # dev region:
              - master
              - test
              - dev
